### ISSUE TITLE
Welcome to newcss Discussions!

### ISSUE THREAD

**Issue by cssmiror** [cssmiror/newcss#2]
### Discussed in https://github.com/cssmiror/newcss/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **cssmiror** November 13, 2023</sup>
what is top books to leraning css?</div>

**Comment by farid-teymouri** [comment]
> ### Discussed in #1
> Originally posted by **cssmiror** November 13, 2023 what is top books to leraning css?

CSS: The Missing Manual" by David Sawyer McFarland
